---

- name: Checking that worker node alredy joined to the primary master node
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_conf

- name: Joining worker nodes to master nodes
  shell: "{{ hostvars[groups['master_nodes'][0]].worker_join_command }}"
  when: not k8s_conf.stat.exists
