---

- name: Installing deps for kubeadm
  become: true
  apt:
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Adding k8s gpg key
  include_tasks:
    file: gpg_key.yml

- name: Installing kube tools
  include_tasks:
    file: kube_tools.yml
