---
- hosts: master_nodes
  become: true
  roles:
    - containerd
    - kube_tools

- hosts: master_nodes
  become: true
  vars_files:
    - vars/kubeadm_init.yml
  roles:
    - { role: init_first_master, when: "groups['master_nodes'][0] == inventory_hostname"}
