---
- hosts: all
  become: true
  roles:
    - containerd
    - kube_tools

- hosts: master_nodes
  become: true
  vars_files:
    - vars/kubeadm_init.yml
  roles:
    - { role: init_primary_master, when: "groups['master_nodes'][0] == inventory_hostname"}
    - { role: join_master_nodes, when: "groups['master_nodes'][0] != inventory_hostname"}

- hosts: worker_nodes
  become: true
  roles:
    - join_worker_nodes
