---

- name: Checking that kubeadm initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_conf

- name: kubeadm init ...
  shell: |
    kubeadm init --cri-socket {{ container_runtime_socket }} --pod-network-cidr={{ pod_network_cidr }} --control-plane-endpoint={{ control_plane_endpoint }}
  when: not k8s_conf.stat.exists

- name: Declaring join command for rest master nodes
  shell: |
    echo $(kubeadm token create --print-join-command) --control-plane --certificate-key $(sudo kubeadm init phase upload-certs --upload-certs | grep -vw -e certificate -e Namespace)
  register: master_join_command

- name: Setting join command for rest master nodes
  set_fact:
    master_join_command: "{{ master_join_command.stdout_lines[0] }}"

- name: Declaring join command for worker nodes
  shell: |
    echo $(kubeadm token create --print-join-command)
  register: worker_join_command

- name: Setting join command for worker nodes
  set_fact:
    worker_join_command: "{{ worker_join_command.stdout_lines[0] }}"

- name: Creating kube config dir
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory

- name: Copying kube config to created dir
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: true
    dest: /home/ubuntu/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
