---
    
- name: Creating keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Downloading docker gpg key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Adding Docker's repository to APT sources list
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

#- name: "Add Docker's official GPG key to apt"
#  apt_key:
#    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
#    url: https://download.docker.com/linux/ubuntu/gpg
#    # Key destination path
#    keyring: /etc/apt/keyrings/docker.gpg
#    state: present

#- name: Downloading docker gpg key
#  block:
#    - name: Download Docker gpg key
#      ansible.builtin.get_url:
#        url: https://download.docker.com/linux/ubuntu/gpg
#        dest: /etc/apt/keyrings/docker.asc
#
#    - name: De-Armor Docker GPG key
#      shell:  gpg --dearmor < /etc/apt/keyrings/docker.asc > sudo /etc/apt/keyrings/docker.gpg
#
#    - name: Add Docker's repository to APT sources list
#      apt_repository:
#        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable"
#        state: present
