---

- name: Forwarding IPv4 and letting iptables see bridged traffic
  include_tasks:
    file: net_modules.yml

- name: Installing deps for containerd
  become: true
  apt:
    update_cache: yes
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Adding docker gpg key
  include_tasks:
    file: gpg_key.yml

- name: Installing containerd
  include_tasks:
    file: containerd.yml
