---

- name: Adding overlay, br_netfilter modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Enabling overlay module
  modprobe:
    name: overlay
    state: present

- name: Enabling br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Copying k8s.conf to sysctl.d dir 
  copy:
    src: "{{ role_path }}/files/containerruntime/containerd/k8s.conf"
    dest: /etc/sysctl.d/k8s.conf

- name: Applying sysctl params
  sysctl:
    name: "{{ item }}"
    value: 1
    reload: true
    state: present
  loop: "{{ sysctl }}"
